<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_payment"
 *
 * Auto generated by Extension Builder 2016-01-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title'            => 'tollwerk Payment Plugins',
    'description'      => 'Stripe & PayPal payment platform plugins',
    'category'         => 'plugin',
    'author'           => 'Joschi Kuphal',
    'author_email'     => 'joschi@tollwerk.de',
    'state'            => 'beta',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '1.0.0',
    'constraints'      => array(
        'depends'   => array(
            'php'                => '7.0.0-',
            'typo3'              => '9.5.0-',
            'static_info_tables' => '6.7.0-',
        ),
        'conflicts' => array(),
        'suggests'  => array(),
    ),
);
