<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_payment"
 *
 * Auto generated by Extension Builder 2016-01-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tollwerk Payment Plugins',
	'description' => 'Stripe & PayPal payment platform plugins',
	'category' => 'plugin',
	'author' => 'Joschi Kuphal',
	'author_email' => 'joschi@tollwerk.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.4.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);